# https://tinylog.org/v2/configuration/
# The launcher uses this to avoid any conflicts with Log4j used in the server environment
writerConsole = console
writerConsole.level = info
writerConsole.format=[{date:HH:mm:ss}] [{thread}/{level}]: {message}

writerDebug = rolling file
writerDebug.level = trace
writerDebug.format=[{date:HH:mm:ss}] [{thread}/{level}]: {message}
writerDebug.file = ignite-logs/debug_launcher-{count}.log
writerDebug.latest = ignite-logs/debug_launcher.log
writerDebug.charset = UTF-8
writerDebug.convert = gzip
writerDebug.backups = 4
writerDebug.policy = startup, size: 200mb
